# Generated by Django 3.1.3 on 2020-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag', models.TextField()),
                ('tweet_id', models.BigIntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_creation', models.DateTimeField()),
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('favorite_count', models.BigIntegerField()),
                ('retweet_count', models.BigIntegerField()),
                ('retweet', models.BigIntegerField()),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterList',
            fields=[
                ('slug', models.TextField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('uri', models.URLField()),
                ('subscriber_count', models.BigIntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('description', models.TextField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.URLField()),
                ('tweet_id', models.BigIntegerField()),
                ('type', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField()),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('screen_name', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField()),
                ('friends_count', models.BigIntegerField()),
                ('listed_count', models.BigIntegerField()),
                ('favourites_count', models.BigIntegerField()),
                ('statuses_count', models.BigIntegerField()),
                ('avatar', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
