# Generated by Django 3.1.3 on 2020-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetUrl',
            fields=[
                ('url', models.URLField()),
                ('tweet_id', models.BigIntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserUrl',
            fields=[
                ('url', models.URLField()),
                ('user_id', models.BigIntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.AlterField(
            model_name='mention',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
