# Generated by Django 3.1.3 on 2020-11-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20201126_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweet',
            new_name='retweet_id',
        ),
    ]
