# Generated by Django 3.1.3 on 2020-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20201127_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
