# Generated by Django 3.1.3 on 2020-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20201127_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('source', models.BigIntegerField()),
                ('target', models.BigIntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
